// <auto-generated />
namespace FootballOracle.Models.Migrations.Pf
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class CompetitionVCompetitionTypeMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CompetitionVCompetitionTypeMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201411241507296_CompetitionVCompetitionTypeMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
