// <auto-generated />
namespace FootballOracle.Models.Migrations.Pf
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class TeamVTeamNameNotRequiredMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TeamVTeamNameNotRequiredMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201411061247063_TeamVTeamNameNotRequiredMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
